export {TentangFormasi} from './Tentang'
export {KontakFormasi} from './Kontak'
export {BerandaFormasi} from './Beranda'
export {ImagePengurus}  from './Pengurus'
export {ImageKeputusan} from './Keputusan'
export {AlbumFormasi }  from './Album'
